<?php
/**
 * Sidebar Component
 * 
 * Required variables:
 * @var string|null $serviceId - Current service ID
 * @var string $section - Current section (secrets/history/etc)
 * @var array $groupedServices - Services organized by group
 * @var string $csrfToken - CSRF token
 */
$currentSection = $section ?? 'secrets';
?>
<aside class="sidebar">
    <div class="sidebar-brand">
        <img src="/favicon.svg" alt="" class="brand-mark" width="32" height="32">
        Railway Secrets
    </div>

    <div class="sidebar-section-label">Project</div>
    <nav>
          <a href="/?section=overview" class="nav-link js-overview-nav <?= $currentSection === 'overview' ? 'active' : '' ?>"
              hx-get="/?section=overview"
              hx-target="#mainContent"
              hx-swap="outerHTML"
              hx-push-url="true"
              hx-indicator="#mainContentLoading">
                <i data-lucide="layout-dashboard" style="width:14px;height:14px;"></i>
                Overview
          </a>
          <a href="/?section=secrets" class="nav-link js-scope-nav <?= ($currentSection === 'secrets' && !$serviceId) ? 'active' : '' ?>"
              hx-get="/?section=secrets"
           hx-target="#mainContent"
           hx-swap="outerHTML"
           hx-push-url="true"
           hx-indicator="#mainContentLoading"
           data-service-id="">
            <i data-lucide="layers" style="width:14px;height:14px;"></i>
            Global Variables
        </a>
        <a href="/managed"
           class="nav-link js-managed-nav <?= $currentSection === 'managed' ? 'active' : '' ?>"
           hx-get="/managed"
           hx-target="#mainContent"
           hx-swap="outerHTML"
           hx-push-url="true"
           hx-indicator="#mainContentLoading">
            <i data-lucide="shield-check" style="width:14px;height:14px;"></i>
            Managed
        </a>
        <?php $historyHref = $serviceId ? '/?serviceId=' . urlencode((string)$serviceId) . '&section=history' : '/?section=history'; ?>
        <a href="<?= htmlspecialchars($historyHref, ENT_QUOTES, 'UTF-8') ?>"
           class="nav-link js-history-nav <?= $currentSection === 'history' ? 'active' : '' ?>"
           hx-get="<?= htmlspecialchars($historyHref, ENT_QUOTES, 'UTF-8') ?>"
           hx-target="#mainContent"
           hx-swap="outerHTML"
           hx-push-url="true"
           hx-indicator="#mainContentLoading">
            <i data-lucide="history" style="width:14px;height:14px;"></i>
            Rotation History
        </a>
    </nav>

    <!-- Services grouped -->
    <?php if (!empty($groupedServices)): ?>

    <?php
        // Determine which group (if any) contains the active service.
        $activeGroupName = null;
        foreach ($groupedServices as $gName => $gItems) {
            foreach ($gItems as $svc) {
                if ($serviceId && $svc['id'] === $serviceId) {
                    $activeGroupName = $gName;
                    break 2;
                }
            }
        }
        // Auto-bucket names generated by buildGroupedServices — not user-created groups.
        $autoBuckets = ['Services', 'Ungrouped'];
    ?>

    <div class="sidebar-services-header">
        <span class="sidebar-section-label" style="margin:0;">Group</span>
        <button type="button" class="sidebar-add-group-btn js-create-group" title="Create a new group">
            <i data-lucide="plus" style="width:11px;height:11px;"></i>
        </button>
    </div>

    <div class="sidebar-scroll-area">
        <div class="sidebar-groups" id="sidebarGroups">
            <?php foreach ($groupedServices as $groupName => $groupItems): ?>
                <?php
                    $groupServiceIdsCsv = implode(',', array_map(static fn ($svc) => (string)($svc['id'] ?? ''), $groupItems));
                    $isActiveGroup = ($activeGroupName === $groupName);
                    $groupSlug = 'grp-' . md5($groupName);
                    $isAutoBucket = in_array($groupName, $autoBuckets, true);
                ?>
                <div class="sidebar-group js-sidebar-group <?= $isActiveGroup ? 'is-open' : '' ?>"
                     data-group-slug="<?= htmlspecialchars($groupSlug, ENT_QUOTES, 'UTF-8') ?>">

                    <!-- Group trigger row -->
                    <div class="sidebar-group-trigger">
                        <button type="button"
                                class="sidebar-group-toggle js-group-toggle"
                                aria-expanded="<?= $isActiveGroup ? 'true' : 'false' ?>"
                                title="Expand / collapse">
                            <i data-lucide="chevron-right" class="sidebar-group-chevron" style="width:12px;height:12px;"></i>
                            <span class="sidebar-group-name"><?= htmlspecialchars($groupName) ?></span>
                            <span class="sidebar-group-count"><?= count($groupItems) ?></span>
                        </button>
                        <?php if (!$isAutoBucket): ?>
                        <button type="button"
                                class="sidebar-group-edit js-edit-group"
                                data-group-name="<?= htmlspecialchars($groupName, ENT_QUOTES, 'UTF-8') ?>"
                                data-service-ids="<?= htmlspecialchars($groupServiceIdsCsv, ENT_QUOTES, 'UTF-8') ?>"
                                title="Edit group">
                            <i data-lucide="pencil" style="width:10px;height:10px;"></i>
                        </button>
                        <?php endif; ?>
                    </div>

                    <!-- Collapsible service list -->
                    <nav class="sidebar-group-items">
                        <?php foreach ($groupItems as $svc): ?>
                            <a href="/?serviceId=<?= htmlspecialchars($svc['id'], ENT_QUOTES, 'UTF-8') ?>"
                               class="nav-link js-scope-nav js-grouped-service <?= ($currentSection !== 'history' && $serviceId === $svc['id']) ? 'active' : '' ?>"
                               hx-get="/?serviceId=<?= urlencode($svc['id']) ?>"
                               hx-target="#mainContent"
                               hx-swap="outerHTML"
                               hx-push-url="true"
                               hx-indicator="#mainContentLoading"
                               data-service-id="<?= htmlspecialchars($svc['id'], ENT_QUOTES, 'UTF-8') ?>"
                               data-service-name="<?= htmlspecialchars($svc['name'], ENT_QUOTES, 'UTF-8') ?>"
                               data-group-name="<?= htmlspecialchars($groupName, ENT_QUOTES, 'UTF-8') ?>">
                                <i data-lucide="box" style="width:12px;height:12px;"></i>
                                <?= htmlspecialchars($svc['name']) ?>
                            </a>
                        <?php endforeach; ?>
                    </nav>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

    <?php endif; ?>

    <div class="sidebar-footer">
        <a href="/docs" class="nav-link js-docs-nav <?= ($currentSection === 'docs' || strpos($_SERVER['REQUEST_URI'] ?? '', '/docs') === 0) ? 'active' : '' ?>">
            <i data-lucide="book-open" style="width:14px;height:14px;"></i>
            Docs
        </a>
        <a href="/about"
           class="nav-link js-about-nav <?= ($currentSection === 'about' || strpos($_SERVER['REQUEST_URI'] ?? '', '/about') === 0) ? 'active' : '' ?>"
           hx-get="/about"
           hx-target="#mainContent"
           hx-swap="outerHTML"
           hx-push-url="true"
           hx-indicator="#mainContentLoading">
            <i data-lucide="info" style="width:14px;height:14px;"></i>
            About
        </a>
        <form method="POST" action="/logout" style="margin:0;">
            <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken ?? '', ENT_QUOTES, 'UTF-8') ?>">
            <button type="submit" class="nav-link nav-link-btn danger">
                <i data-lucide="log-out" style="width:14px;height:14px;"></i>
                Logout
            </button>
        </form>
    </div>
</aside>
